spring.application.name=evotingsystem

spring.datasource.url=jdbc:mysql://localhost:3306/evoting?serverTimezone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

# Thymeleaf template configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

# Session management
server.servlet.session.timeout=30m